[package]
name = "engine_app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "CLI and API app for engine-zoo"
build = "build.rs"

[[bin]]
name = "engine-zoo"
path = "src/bin/engine-zoo.rs"

[[bin]]
name = "train"
path = "src/bin/train.rs"

[[bin]]
name = "eval"
path = "src/bin/eval.rs"

[[bin]]
name = "engine-zoo-uci"
path = "src/bin/engine-zoo-uci.rs"

[dependencies]
alphazero = { path = "../alphazero" }
search = { path = "../search" }
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
checkpoint-eval = { path = "../evaluations" }
engine_core = { path = "../core" }
games = { path = "../games" }
libc.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tch.workspace = true
tokio.workspace = true
tower-http.workspace = true
