#!/usr/bin/env python3
"""Run the resumable CUDA self-play batcher/leaf-batch parameter screen.

This is deliberately benchmark tooling: it writes generated experiment files
and reports beneath its output directory and never changes a production recipe.
"""

from __future__ import annotations

import argparse
import csv
import itertools
import json
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass(frozen=True)
class Case:
    threads: int
    leaf_batch_size: int
    preferred_batch_size: int
    wait_milliseconds: int

    @property
    def name(self) -> str:
        return (
            f"threads{self.threads}-leaf{self.leaf_batch_size}"
            f"-preferred{self.preferred_batch_size}-wait{self.wait_milliseconds}ms"
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("benchmark-results/root-gumbel-256-64-self-play-sweep"),
        help="Directory for generated TOML, per-case JSON, and aggregate reports.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print cases without running them.")
    parser.add_argument("--limit", type=int, help="Run at most this many incomplete cases.")
    parser.add_argument(
        "--engine-bench",
        type=Path,
        default=Path("target/release/engine-bench"),
        help="Path to the already-built engine-bench executable.",
    )
    return parser.parse_args()


def cases() -> list[Case]:
    return [
        Case(*values)
        for values in itertools.product((16, 24, 32), (4, 8, 16), (32, 64, 128), (1, 2, 4))
    ]


def experiment_toml(case: Case) -> str:
    return f'''# Generated by scripts/sweep_cuda_root_gumbel.py. Do not edit.
format_version = 3
seed = 1

[model]
architecture = "chess-se"
history = "one"
blocks = 12
channels = 128
se_hidden = 16
value_head = {{ wdl = {{ hidden = 128 }} }}

[self_play]
num_games = 10
threads = {case.threads}
max_moves = 512
progress_every = 0
evaluation_cache_entries = 1000000

[self_play.search]
algorithm = "root-gumbel-puct"
leaf_batch_size = {case.leaf_batch_size}

[self_play.budget_schedule.playout-cap-randomization]
full_probability = 0.25
fast_policy_weight = 0.0

[self_play.budget_schedule.playout-cap-randomization.full.gumbel]
simulations = 256
max_considered_actions = 16

[self_play.budget_schedule.playout-cap-randomization.fast.gumbel]
simulations = 64
max_considered_actions = 8

[training]
# This screen intentionally measures self-play/inference only. Training has a
# separate workload and must not obscure comparisons between batcher settings.
train_steps = 0
progress_every = 0

[inference]
precision = "fp16"
preferred_batch_size = {case.preferred_batch_size}
max_batch_size = 256
max_queued_states = 4096

[inference.max_wait]
milliseconds = {case.wait_milliseconds}
'''


def metrics(report_path: Path, case: Case) -> dict[str, object]:
    report = json.loads(report_path.read_text())
    sample = report["samples"][0]
    data = sample["metrics"]
    batch = data["batch_stats"]
    return {
        **asdict(case),
        "name": case.name,
        "elapsed_seconds": sample["elapsed_ns"] / 1_000_000_000,
        "positions_per_second": data["positions_per_second"],
        "inference_states_per_second": data["inference_states_per_second"],
        "average_inference_batch": batch["average_inference_batch"],
        "maximum_inference_batch": batch["maximum_inference_batch"],
        "report": str(report_path),
    }


def write_aggregate(output_dir: Path, completed: list[dict[str, object]]) -> None:
    completed.sort(key=lambda item: float(item["inference_states_per_second"]), reverse=True)

    (output_dir / "aggregate.json").write_text(json.dumps(completed, indent=2) + "\n")

    fields = list(completed[0]) if completed else [*asdict(Case(0, 0, 0, 0)), "name", "elapsed_seconds", "positions_per_second", "inference_states_per_second", "average_inference_batch", "maximum_inference_batch", "report"]
    with (output_dir / "aggregate.csv").open("w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fields)
        writer.writeheader()
        writer.writerows(completed)


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir
    configs = output_dir / "configs"
    results = output_dir / "results"
    all_cases = cases()

    if not args.dry_run and not args.engine_bench.is_file():
        raise SystemExit(
            f"engine-bench executable not found: {args.engine_bench}. Build it with "
            "cargo build --release -p engine-bench, or pass --engine-bench."
        )

    configs.mkdir(parents=True, exist_ok=True)
    results.mkdir(parents=True, exist_ok=True)
    completed: list[dict[str, object]] = []
    pending: list[Case] = []

    for case in all_cases:
        result_path = results / f"{case.name}.json"
        if result_path.is_file():
            try:
                completed.append(metrics(result_path, case))
                continue
            except (KeyError, ValueError, json.JSONDecodeError):
                print(f"re-running incomplete or invalid result: {result_path}", file=sys.stderr)
        pending.append(case)

    if args.dry_run:
        for index, case in enumerate(pending, start=1):
            print(f"{index}/{len(pending)} {case.name}")
        print(f"completed={len(completed)} pending={len(pending)} total={len(all_cases)}")
        return 0

    for index, case in enumerate(pending, start=1):
        if args.limit is not None and index > args.limit:
            break

        config_path = configs / f"{case.name}.toml"
        result_path = results / f"{case.name}.json"
        config_path.write_text(experiment_toml(case))

        command = [
            str(args.engine_bench), "iteration", "--experiment", str(config_path),
            "--device", "cuda", "--samples", "1", "--name", case.name,
            "--output", str(result_path), "--human",
        ]
        print(f"[{index}/{len(pending)}] {' '.join(command)}", flush=True)
        subprocess.run(command, check=True)

        row = metrics(result_path, case)
        completed.append(row)
        write_aggregate(output_dir, completed)
        print(
            "  complete: "
            f"{row['elapsed_seconds']:.2f}s, {row['positions_per_second']:.1f} positions/s, "
            f"{row['inference_states_per_second']:.1f} states/s, "
            f"avg batch {row['average_inference_batch']:.1f}",
            flush=True,
        )

    write_aggregate(output_dir, completed)
    print(f"completed={len(completed)} pending={len(all_cases) - len(completed)} total={len(all_cases)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
