#!/usr/bin/env python3
"""Run the fixed-checkpoint H4 TensorRT self-play batching screen.

This is benchmark-only tooling. It generates the nine H4 Root-Gumbel configs,
leaves production recipes untouched, and resumes from valid JSON
reports already present in its output directory.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path


BASE_EXPERIMENT = Path("benchmarks/configs/default-chess-h4-cuda-500.toml")


@dataclass(frozen=True)
class Case:
    preferred_batch_size: int
    wait_milliseconds: int

    @property
    def name(self) -> str:
        return f"preferred{self.preferred_batch_size}-wait{self.wait_milliseconds}ms"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", type=Path, required=True,
                        help="Safetensors source checkpoint recorded in each report.")
    parser.add_argument("--tensor-rt-module", type=Path, required=True,
                        help="TensorRT TorchScript module compiled from --checkpoint.")
    parser.add_argument("--output-dir", type=Path,
                        default=Path("benchmark-results/tensorrt-h4-batching-sweep"))
    parser.add_argument("--engine-bench", type=Path,
                        default=Path("target/release/engine-bench"))
    parser.add_argument("--samples", type=int, default=1,
                        help="Fresh 64-game samples per case.")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--limit", type=int, help="Run at most this many incomplete cases.")
    parser.add_argument(
        "--libtorch",
        type=Path,
        default=environment_path("LIBTORCH"),
        help="LibTorch root directory (default: $LIBTORCH).",
    )
    parser.add_argument(
        "--trt-site",
        type=Path,
        default=environment_path("TRT_SITE"),
        help="Python site-packages directory containing Torch-TensorRT (default: $TRT_SITE).",
    )
    return parser.parse_args()


def environment_path(name: str) -> Path | None:
    """Return a non-empty path from an optional environment variable."""
    value = os.environ.get(name)
    return Path(value) if value else None


def cases() -> list[Case]:
    return [Case(batch, wait) for batch in (32, 64, 128) for wait in (1, 2, 4)]


def experiment_toml(case: Case) -> str:
    """Keep the checked-in H4 recipe intact except for the screened settings."""
    if not BASE_EXPERIMENT.is_file():
        raise SystemExit(f"missing H4 baseline experiment: {BASE_EXPERIMENT}")

    source = BASE_EXPERIMENT.read_text()
    source = re.sub(
        r"(?m)^preferred_batch_size = \d+$",
        f"preferred_batch_size = {case.preferred_batch_size}",
        source,
    )
    source = re.sub(
        r"(?m)^milliseconds = \d+$",
        f"milliseconds = {case.wait_milliseconds}",
        source,
    )
    return "# Generated by sweep_tensorrt_h4_batching.py. Do not edit.\n" + source


def runtime_environment(libtorch: Path | None, trt_site: Path | None) -> dict[str, str]:
    if libtorch is None:
        raise SystemExit("missing LibTorch: pass --libtorch or set LIBTORCH")
    if trt_site is None:
        raise SystemExit("missing Torch-TensorRT site-packages: pass --trt-site or set TRT_SITE")

    torch_lib = libtorch / "lib"
    trt_lib = trt_site / "torch_tensorrt" / "lib"
    nvidia_lib = trt_site / "tensorrt_libs"

    for path in (torch_lib, trt_lib, nvidia_lib):
        if not path.is_dir():
            raise SystemExit(f"TensorRT runtime directory does not exist: {path}")

    environment = os.environ.copy()
    library_paths = [str(torch_lib), str(trt_lib), str(nvidia_lib)]
    if existing := environment.get("LD_LIBRARY_PATH"):
        library_paths.append(existing)
    environment["LD_LIBRARY_PATH"] = ":".join(library_paths)

    torch_preload = torch_lib / "libtorch.so"
    trt_preload = trt_lib / "libtorchtrt.so"
    for path in (torch_preload, trt_preload):
        if not path.is_file():
            raise SystemExit(f"TensorRT runtime library does not exist: {path}")

    preload = [str(torch_preload), str(trt_preload)]
    if existing := environment.get("LD_PRELOAD"):
        preload.append(existing)
    environment["LD_PRELOAD"] = ":".join(preload)
    return environment


def report_row(result_path: Path, case: Case) -> dict[str, object]:
    report = json.loads(result_path.read_text())
    sample = report["samples"][0]
    metrics = sample["metrics"]
    batcher = metrics["batcher"]
    return {
        "name": case.name,
        "preferred_batch_size": case.preferred_batch_size,
        "wait_milliseconds": case.wait_milliseconds,
        "elapsed_seconds": sample["elapsed_ns"] / 1_000_000_000,
        "games_per_second": metrics["games_per_second"],
        "positions_per_second": metrics["positions_per_second"],
        "backend_evaluations_per_second": metrics["backend_evaluations_per_second"],
        "inference_states_per_second": batcher["states_per_second"],
        "average_global_batch": batcher["average_global_batch"],
        "maximum_global_batch": batcher["maximum_global_batch"],
        "backend_execution_seconds": batcher["backend_execution_seconds"],
        "queue_wait_seconds": batcher["queue_wait_seconds"],
        "report": str(result_path),
    }


def write_aggregate(output_dir: Path, rows: list[dict[str, object]]) -> None:
    rows.sort(key=lambda row: float(row["positions_per_second"]), reverse=True)
    (output_dir / "aggregate.json").write_text(json.dumps(rows, indent=2) + "\n")
    with (output_dir / "aggregate.csv").open("w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=list(rows[0]) if rows else [])
        if rows:
            writer.writeheader()
            writer.writerows(rows)


def main() -> int:
    args = parse_args()
    if not args.checkpoint.is_file():
        raise SystemExit(f"checkpoint does not exist: {args.checkpoint}")
    if not args.tensor_rt_module.is_file():
        raise SystemExit(f"TensorRT module does not exist: {args.tensor_rt_module}")
    if not args.dry_run and not args.engine_bench.is_file():
        raise SystemExit(f"engine-bench executable not found: {args.engine_bench}")

    output_dir = args.output_dir
    results_dir = output_dir / "results"
    configs_dir = output_dir / "configs"
    results_dir.mkdir(parents=True, exist_ok=True)
    configs_dir.mkdir(parents=True, exist_ok=True)
    completed: list[dict[str, object]] = []
    pending: list[Case] = []

    for case in cases():
        result_path = results_dir / f"{case.name}.json"
        if result_path.is_file():
            try:
                completed.append(report_row(result_path, case))
                continue
            except (KeyError, ValueError, json.JSONDecodeError):
                print(f"re-running incomplete result: {result_path}")
        pending.append(case)

    if args.dry_run:
        for case in pending:
            print(f"{case.name}: {configs_dir / (case.name + '.toml')}")
        print(f"completed={len(completed)} pending={len(pending)} total={len(cases())}")
        return 0

    environment = runtime_environment(args.libtorch, args.trt_site)
    for index, case in enumerate(pending, start=1):
        if args.limit is not None and index > args.limit:
            break
        result_path = results_dir / f"{case.name}.json"
        config_path = configs_dir / f"{case.name}.toml"
        config_path.write_text(experiment_toml(case))
        command = [
            str(args.engine_bench), "chess-self-play",
            "--experiment", str(config_path),
            "--checkpoint", str(args.checkpoint),
            "--tensor-rt-module", str(args.tensor_rt_module),
            "--backend", "tensor-rt", "--games", "64", "--samples", str(args.samples),
            "--device", "cuda", "--output", str(result_path), "--human",
        ]
        print(f"[{index}/{len(pending)}] {' '.join(command)}", flush=True)
        subprocess.run(command, check=True, env=environment)
        completed.append(report_row(result_path, case))
        write_aggregate(output_dir, completed)

    write_aggregate(output_dir, completed)
    print(f"completed={len(completed)} pending={len(cases()) - len(completed)} total={len(cases())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
